[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['cd backend && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['cd backend && pnpm run prisma:generate', 'cd backend && pnpm run build']

[start]
cmd = 'cd backend && pnpm run prisma:migrate && node dist/main'
